### ISSUE TITLE
Required spacy model en_core_web_md not in conda env

### ISSUE THREAD

**Issue by hugowangler** [rpa-tomorrow/substorm-nlp#92]
# Expected behavior
Should be able to start the CLI after running the setup script

# Actual behavior
Error since `en_core_web_md` is missing.
```bash
Loading...
Traceback (most recent call last):
  File "lib/cli/cli.py", line 27, in <module>
    cli()
  File "lib/cli/cli.py", line 13, in cli
    n = nlp.NLP(MODEL_NAME)
  File "./lib/nlp/nlp.py", line 9, in __init__
    self.sim_model = spacy.load("en_core_web_md")
  File "/home/hugo/miniconda3/envs/substorm-nlp/lib/python3.8/site-packages/spacy/__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "/home/hugo/miniconda3/envs/substorm-nlp/lib/python3.8/site-packages/spacy/util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_md'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

# Steps to reproduce
1.
2.
3.

# Additional context
Have to update the substorm-nlp.yml file.

**Comment by banunkers** [comment]
Probably better to add the missing model to the setup script directly since the sm model is installed in the script anyway.
